apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-pod-labels
  annotations:
    policies.kyverno.io/title: Add Default Pod Labels
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/description: >-
      Auto-injects team=platform and env=lab labels onto every pod
      that doesn't already set them.
spec:
  rules:
    - name: add-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              +(team): "platform"
              +(env): "lab"
